server:
  port:

app:
  base-url:

spring:
  application:
    name: "Ludwigit"
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/ludwigit
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

base62:
  alphabet: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

hashids:
  min-length:
  salt:
